Número = int(input('Digite um número para saber sua tabuada: '))
print('_'*12)
print('TABUADA DO NÚMERO {}'.format(Número))
print('_'*12)
print('{} x {} = {}'.format(Número, 1, Número*1))
print('{} x {} = {}.'.format(Número, 2, Número*2))
print('{} x {} = {}'.format(Número, 3, Número*3))
print('{} x {} = {}'.format(Número, 4, Número*4))
print('{} x {} = {}'.format(Número, 5,Número*5))
print('{} x {} = {}'.format(Número, 6,Número*6))
print('{} x {} = {}'.format(Número, 7,Número*7))
print('{} x {} = {}'.format(Número, 8,Número*8))
print('{} x {} = {}'.format(Número, 9,Número*9))
print('{} x {} = {}'.format(Número, 10,Número*10))
print('_'*12)