a = (input('Digite Algo: '))
print('O Tipo Primitivo Desse Valor é {} '.format(a), type(a))
print('É somente espaços: {} '.format(a), a.isspace())
print('É um número: {} '.format(a), a.isnumeric())
print('É alfabético: {} '.format(a), a.isalpha())
print('É alfanumérico {} '.format(a), a.isalnum())
print('Está em letras maiúsculas: {} '.format(a), a.isupper())
print('está em letras minúsculas {} '.format(a), a.islower())
print('Está Capitalizado: {} '.format(a), a.istitle())